version: '3.8'

services:
  adminer:
    image: 'adminer:${ADMINER_IMAGE_TAG}'
    container_name: 'adminer-container'
    restart: unless-stopped

    env_file:
      - .envs/adminer.env

    networks:
      - common-net

    ports:
      - ${ADMINER_PUBLISH_PORT}:8080