version: '3.8'

services:
  mysql:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=1

    ports:
      - ${MYSQL_PUBLISH_PORT}:3306

  redis:
    ports:
      - ${REDIS_PUBLISH_PORT}:6379

  adminer:
    ports:
      - ${ADMINER_PUBLISH_PORT}:8080