version: '3.8'

services:
  mysql:
    image: 'mysql:${MYSQL_IMAGE_TAG}'
    container_name: 'mysql-8-container'
    restart: unless-stopped
    volumes:
      - common-mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=1

    env_file:
      - .envs/mysql.env

    networks:
      common-net:
        aliases:
          - common-mysql
    ports:
      - ${MYSQL_PUBLISH_PORT}:3306
